export enum ComponentType {
  Text = 'text',
  Image = 'image',
  Link = 'link',
  Button = 'button',
  Card = 'card',
  Form = 'form',
  List = 'list',
  ListItem = 'list-item',
  Table = 'table',
  Input = 'input',
  Label = 'label',
  Iframe = 'iframe',
  Container = 'container',
  // TODO: fill and implement the rest of the components
  CustomHTML = 'custom-html',
  CustomCSS = 'custom-css',
  CustomJS = 'custom-js',
}

export enum ComponentEditType {
  Text = ComponentType.Text,
  Image = ComponentType.Image,
  Link = ComponentType.Link,
  Button = ComponentType.Button,
  Card = ComponentType.Card,
  Form = ComponentType.Form,
  List = ComponentType.List,
  ListItem = ComponentType.ListItem,
  Table = ComponentType.Table,
  Input = ComponentType.Input,
  Label = ComponentType.Label,
  Iframe = ComponentType.Iframe,
  Container = ComponentType.Container,
  CustomHTML = ComponentType.CustomHTML,
  CustomCSS = ComponentType.CustomCSS,
  CustomJS = ComponentType.CustomJS,
}
